"use client";

import { useEffect, useState, useCallback, useRef } from "react";
import {
  Box,
  Container,
  Heading,
  Text,
  VStack,
  HStack,
  Input,
  Slider,
  Flex,
  Separator,
  Grid,
  GridItem,
  Select,
  createListCollection,
  Switch,
  Spinner,
} from "@chakra-ui/react";
import { Button } from "@/components/ui/button";
import { Field } from "@/components/ui/field";
import { FiArrowLeft, FiSave, FiCopy } from "react-icons/fi";
import Link from "next/link";
import { toaster, Toaster } from "@/components/ui/toaster";
import { useTranslation } from '@/lib/i18n'

// ─── Types ────────────────────────────────────────────────────────────────────

interface ChatVisualConfig {
  chat_bgColor: string;
  chat_bgBlur: string;
  chat_borderRadius: string;
  chat_borderColor: string;
  chat_borderWidth: string;
  chat_textColor: string;
  chat_fontSize: string;
  chat_maxMessages: string;
  chat_position: string;
  chat_font: string;
  chat_enterAnimation: string;
}

const DEFAULT_CONFIG: ChatVisualConfig = {
  chat_bgColor: "rgba(20,20,20,0.6)",
  chat_bgBlur: "10",
  chat_borderRadius: "12",
  chat_borderColor: "rgba(255,255,255,0.1)",
  chat_borderWidth: "1",
  chat_textColor: "#e0e0e0",
  chat_fontSize: "14",
  chat_maxMessages: "10",
  chat_position: "bottom-left",
  chat_font: "Inter",
  chat_enterAnimation: "slideIn",
};

// ─── Constants ────────────────────────────────────────────────────────────────

const FONTS = [
  "Inter",
  "Roboto",
  "Oswald",
  "Nunito",
  "Rajdhani",
  "Bebas Neue",
  "Monospace",
];
const ANIMATIONS = [
  { label: "Slide In", value: "slideIn" },
  { label: "Fade In", value: "fadeIn" },
  { label: "Zoom In", value: "zoomIn" },
  { label: "Bounce In", value: "bounceIn" },
];

const fontCollection = createListCollection({
  items: FONTS.map((f) => ({ label: f, value: f })),
});
const animCollection = createListCollection({ items: ANIMATIONS });

// ─── Fake messages ────────────────────────────────────────────────────────────

const FAKE_MESSAGES = [
  {
    id: "1",
    username: "YouTubeFan",
    color: "#ff0000",
    message: "Le stream est super ! 🔥",
    badges: [],
  },
  {
    id: "2",
    username: "KomsterrYT",
    color: "#ffd93d",
    message: "Bienvenue sur le chat YouTube !",
    badges: [],
  },
  {
    id: "3",
    username: "Viewer123",
    color: "#4ecdc4",
    message: "Trop bien l'overlay !",
    badges: [],
  },
];

// ─── OBS CSS Generator ────────────────────────────────────────────────────────

function generateYoutubeCSS(config: ChatVisualConfig) {
  return `
/* OBS Custom CSS for YouTube Chat */
/* Generated by StreamTools */

@import url('https://fonts.googleapis.com/css2?family=${config.chat_font.replace(" ", "+")}:wght@400;700&display=swap');

body {
  background-color: transparent !important;
}

yt-live-chat-renderer {
  background-color: transparent !important;
}

yt-live-chat-app {
  background: transparent !important;
}

#item-scroller {
  overflow: hidden !important;
}

/* Hide header, footer, and other clutter */
yt-live-chat-header-renderer,
yt-live-chat-message-input-renderer,
yt-live-chat-mode-change-message-renderer,
yt-live-chat-viewer-engagement-message-renderer,
#ticker {
  display: none !important;
}

/* Base message styling */
yt-live-chat-text-message-renderer {
  background-color: ${config.chat_bgColor} !important;
  backdrop-filter: blur(${config.chat_bgBlur}px) !important;
  -webkit-backdrop-filter: blur(${config.chat_bgBlur}px) !important;
  border: ${config.chat_borderWidth}px solid ${config.chat_borderColor} !important;
  border-radius: ${config.chat_borderRadius}px !important;
  padding: 8px 14px !important;
  margin-bottom: 8px !important;
  font-family: '${config.chat_font}', sans-serif !important;
  font-size: ${config.chat_fontSize}px !important;
  color: ${config.chat_textColor} !important;
  /* Animation (Slide In) */
  animation: ${config.chat_enterAnimation} 0.3s ease-out forwards;
}

/* Avatar */
yt-img-shadow, #author-photo {
  display: none !important; /* Hide avatars for a cleaner look matching Twitch overlay */
}

/* Username */
yt-live-chat-author-chip {
  margin-right: 6px !important;
}

#author-name {
  color: inherit !important; /* Will let youtube colored names through or fallback */
  font-size: ${config.chat_fontSize}px !important;
  font-weight: 700 !important;
}

/* Message Text */
#message, #message * {
  color: ${config.chat_textColor} !important;
  font-size: ${config.chat_fontSize}px !important;
  line-height: 1.4 !important;
}

/* Animations injected */
@keyframes slideIn { from { opacity: 0; transform: translateY(20px); } to { opacity: 1; transform: translateY(0); } }
@keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }
@keyframes zoomIn { from { opacity: 0; transform: scale(0.85); } to { opacity: 1; transform: scale(1); } }
@keyframes bounceIn { 
  0% { opacity: 0; transform: translateY(30px); }
  60% { opacity: 1; transform: translateY(-6px); }
  100% { opacity: 1; transform: translateY(0); }
}
`.trim();
}

// ─── Inline Chat Preview ──────────────────────────────────────────────────────

function ChatPreview({ config }: { config: ChatVisualConfig }) {
  const generatedCSS = generateYoutubeCSS(config);

  return (
    <Box
      position="relative"
      w="full"
      h="full"
      overflow="hidden"
      display="flex"
      flexDirection="column"
      justifyContent="flex-end"
      p={4}
      bg="transparent"
      id="yt-preview-container"
    >
      <style
        dangerouslySetInnerHTML={{
          __html: `
        #yt-preview-container yt-live-chat-text-message-renderer {
          display: block;
        }
        ${generatedCSS}
      `,
        }}
      />
      {/* Background pattern matching OBS Preview overlay */}
      <Box
        position="absolute"
        inset={0}
        bg="repeating-linear-gradient(45deg, #111 0px, #111 10px, #1a1a1a 10px, #1a1a1a 20px)"
        zIndex={-1}
      />
      <Text
        position="absolute"
        top={2}
        left={3}
        fontSize="10px"
        color="whiteAlpha.400"
        zIndex={0}
        letterSpacing="wide"
        fontFamily="mono"
      >
        OBS PREVIEW
      </Text>

      {FAKE_MESSAGES.map((msg) => (
        // Mocking YouTube's DOM structure so the CSS applies accurately
        <Box
          key={msg.id}
          style={{ maxWidth: "85%" }}
          // Use dangerouslySetInnerHTML to bypass Chakra/React prop filtering for custom elements
          dangerouslySetInnerHTML={{
            __html: `
            <yt-live-chat-text-message-renderer>
              <yt-live-chat-author-chip style="display:inline-flex; align-items:center;">
                <span id="author-name" style="color: ${msg.color}">${msg.username}</span>
              </yt-live-chat-author-chip>
              <span id="message">${msg.message}</span>
            </yt-live-chat-text-message-renderer>
          `,
          }}
        />
      ))}
    </Box>
  );
}

// ─── Main Page ────────────────────────────────────────────────────────────────

export default function YouTubeChatCustomize() {
  const { t } = useTranslation()
  const [config, setConfig] = useState<ChatVisualConfig>(DEFAULT_CONFIG);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);

  // Load existing settings
  useEffect(() => {
    async function load() {
      try {
        const res = await fetch("/api/settings");
        const data = await res.json();
        if (data["youtube-chat"]) {
          setConfig((prev) => ({ ...prev, ...data["youtube-chat"] }));
        }
      } catch (err) {
        console.error("Failed to load settings", err);
      } finally {
        setLoading(false);
      }
    }
    load();
  }, []);

  const update = useCallback((key: keyof ChatVisualConfig, value: string) => {
    setConfig((prev) => ({ ...prev, [key]: value }));
  }, []);

  const saveSettings = async () => {
    setSaving(true);
    try {
      await fetch("/api/settings", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ key: "youtube-chat", value: config }),
      });
      toaster.create({
        title: t('settings.saved'),
        description: "L'overlay du chat YouTube a été mis à jour.",
        type: "success",
      });
    } catch (err) {
      toaster.create({
        title: t('common.error'),
        description: "Impossible de sauvegarder",
        type: "error",
      });
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return (
      <Flex minH="50vh" justify="center" align="center">
        <Spinner size="xl" />
      </Flex>
    );
  }

  return (
    <Box minH="100vh" bg="gray.50" _dark={{ bg: "gray.900" }} pb={20}>
      <Toaster />
      <Box
        bg="white"
        _dark={{ bg: "gray.900", borderColor: "gray.700" }}
        borderBottom="1px solid"
        borderColor="gray.200"
        position="sticky"
        top={14}
        zIndex={10}
        mb={8}
      >
        <Container maxW="7xl">
          <Flex h={14} alignItems="center" justify="space-between">
            <HStack gap={4}>
              <Button asChild variant="ghost" size="sm">
                <Link href="/dashboard">
                  <FiArrowLeft /> Dashboard
                </Link>
              </Button>
              <Separator orientation="vertical" h={6} />
              <Heading size="md">{t('youtube.personalization')}</Heading>
            </HStack>
            <Button
              colorPalette="red"
              size="sm"
              onClick={saveSettings}
              loading={saving}
            >
              <FiSave /> Sauvegarder
            </Button>
          </Flex>
        </Container>
      </Box>

      <Container maxW="7xl">
        <Grid templateColumns={{ base: "1fr", lg: "1fr 1fr" }} gap={8}>
          {/* LEFT — Live Preview */}
          <GridItem>
            <Box position="sticky" top="120px">
              <HStack mb={4} justify="space-between">
                <Heading size="md">👁 Aperçu en temps réel</Heading>
              </HStack>
              <Box
                w="full"
                h={{ base: "400px", lg: "calc(100vh - 200px)" }}
                maxH="800px"
                borderRadius="xl"
                overflow="hidden"
                boxShadow="2xl"
                border="1px solid"
                borderColor="whiteAlpha.100"
                bg="black"
              >
                <ChatPreview config={config} />
              </Box>
            </Box>
          </GridItem>

          {/* RIGHT — Editor */}
          <GridItem>
            <VStack align="stretch" gap={6}>
              {/* ── Typographie ── */}
              <Box
                p={5}
                bg="white"
                _dark={{ bg: "gray.800" }}
                borderRadius="xl"
                shadow="sm"
              >
                <Heading size="sm" mb={3}>
                  ✍️ Typographie
                </Heading>
                <VStack align="stretch" gap={4}>
                  <Field label={t('settings.fontFamily')>
                    <Select.Root
                      collection={fontCollection}
                      value={[config.chat_font]}
                      onValueChange={(e) => update("chat_font", e.value[0])}
                      size="sm"
                    >
                      <Select.HiddenSelect />
                      <Select.Control>
                        <Select.Trigger>
                          <Select.ValueText />
                        </Select.Trigger>
                      </Select.Control>
                      <Select.Positioner>
                        <Select.Content>
                          {fontCollection.items.map((item) => (
                            <Select.Item key={item.value} item={item}>
                              {item.label}
                            </Select.Item>
                          ))}
                        </Select.Content>
                      </Select.Positioner>
                    </Select.Root>
                  </Field>

                  <Box>
                    <Text fontSize="sm" mb={1}>
                      Taille du texte ({config.chat_fontSize}px)
                    </Text>
                    <Slider.Root
                      min={10}
                      max={30}
                      step={1}
                      value={[parseInt(config.chat_fontSize)]}
                      onValueChange={(e) =>
                        update("chat_fontSize", String(e.value[0]))
                      }
                    >
                      <Slider.Control>
                        <Slider.Track>
                          <Slider.Range />
                        </Slider.Track>
                        <Slider.Thumb index={0} />
                      </Slider.Control>
                    </Slider.Root>
                  </Box>

                  <Field label="Couleur du texte">
                    <HStack>
                      <Input
                        type="color"
                        w="50px"
                        p={0}
                        h="36px"
                        value={config.chat_textColor}
                        onChange={(e) =>
                          update("chat_textColor", e.target.value)
                        }
                      />
                      <Input
                        value={config.chat_textColor}
                        onChange={(e) =>
                          update("chat_textColor", e.target.value)
                        }
                        placeholder="#e0e0e0"
                      />
                    </HStack>
                  </Field>
                </VStack>
              </Box>

              {/* ── Apparence des messages ── */}
              <Box
                p={5}
                bg="white"
                _dark={{ bg: "gray.800" }}
                borderRadius="xl"
                shadow="sm"
              >
                <Heading size="sm" mb={3}>
                  🎨 Apparence des messages
                </Heading>
                <VStack align="stretch" gap={4}>
                  <Field label="Couleur de fond">
                    <HStack>
                      <Input
                        type="color"
                        w="50px"
                        p={0}
                        h="36px"
                        value={config.chat_bgColor}
                        onChange={(e) => update("chat_bgColor", e.target.value)}
                      />
                      <Input
                        value={config.chat_bgColor}
                        onChange={(e) => update("chat_bgColor", e.target.value)}
                        placeholder="rgba(20,20,20,0.6)"
                      />
                    </HStack>
                  </Field>

                  <Box>
                    <Text fontSize="sm" mb={1}>
                      Flou d'arrière-plan (Blur) : {config.chat_bgBlur}px
                    </Text>
                    <Slider.Root
                      min={0}
                      max={30}
                      step={1}
                      value={[parseInt(config.chat_bgBlur)]}
                      onValueChange={(e) =>
                        update("chat_bgBlur", String(e.value[0]))
                      }
                    >
                      <Slider.Control>
                        <Slider.Track>
                          <Slider.Range />
                        </Slider.Track>
                        <Slider.Thumb index={0} />
                      </Slider.Control>
                    </Slider.Root>
                  </Box>

                  <Box>
                    <Text fontSize="sm" mb={1}>
                      Arrondi (Border Radius) : {config.chat_borderRadius}px
                    </Text>
                    <Slider.Root
                      min={0}
                      max={30}
                      step={1}
                      value={[parseInt(config.chat_borderRadius)]}
                      onValueChange={(e) =>
                        update("chat_borderRadius", String(e.value[0]))
                      }
                    >
                      <Slider.Control>
                        <Slider.Track>
                          <Slider.Range />
                        </Slider.Track>
                        <Slider.Thumb index={0} />
                      </Slider.Control>
                    </Slider.Root>
                  </Box>

                  <HStack gap={4}>
                    <Field label={t('settings.borderColor')>
                      <HStack>
                        <Input
                          type="color"
                          w="50px"
                          p={0}
                          h="36px"
                          value={config.chat_borderColor}
                          onChange={(e) =>
                            update("chat_borderColor", e.target.value)
                          }
                        />
                        <Input
                          value={config.chat_borderColor}
                          onChange={(e) =>
                            update("chat_borderColor", e.target.value)
                          }
                          placeholder="rgba(255,255,255,0.1)"
                        />
                      </HStack>
                    </Field>
                    <Box w="full">
                      <Text fontSize="sm" mb={1}>
                        Largeur (px)
                      </Text>
                      <Slider.Root
                        min={0}
                        max={5}
                        step={1}
                        value={[parseInt(config.chat_borderWidth)]}
                        onValueChange={(e) =>
                          update("chat_borderWidth", String(e.value[0]))
                        }
                      >
                        <Slider.Control>
                          <Slider.Track>
                            <Slider.Range />
                          </Slider.Track>
                          <Slider.Thumb index={0} />
                        </Slider.Control>
                      </Slider.Root>
                    </Box>
                  </HStack>
                </VStack>
              </Box>

              {/* ── Comportement ── */}
              <Box
                p={5}
                bg="white"
                _dark={{ bg: "gray.800" }}
                borderRadius="xl"
                shadow="sm"
              >
                <Heading size="sm" mb={3}>
                  ⚙️ Comportement
                </Heading>
                <VStack align="stretch" gap={4}>
                  <Box>
                    <Text fontSize="sm" mb={1}>
                      Nombre max de messages : {config.chat_maxMessages}
                    </Text>
                    <Slider.Root
                      min={3}
                      max={30}
                      step={1}
                      value={[parseInt(config.chat_maxMessages)]}
                      onValueChange={(e) =>
                        update("chat_maxMessages", String(e.value[0]))
                      }
                    >
                      <Slider.Control>
                        <Slider.Track>
                          <Slider.Range />
                        </Slider.Track>
                        <Slider.Thumb index={0} />
                      </Slider.Control>
                    </Slider.Root>
                  </Box>
                  <Field label="Animation d'entrée">
                    <Select.Root
                      collection={animCollection}
                      value={[config.chat_enterAnimation]}
                      onValueChange={(e) =>
                        update("chat_enterAnimation", e.value[0])
                      }
                      size="sm"
                    >
                      <Select.HiddenSelect />
                      <Select.Control>
                        <Select.Trigger>
                          <Select.ValueText />
                        </Select.Trigger>
                      </Select.Control>
                      <Select.Positioner>
                        <Select.Content>
                          {animCollection.items.map((item) => (
                            <Select.Item key={item.value} item={item}>
                              {item.label}
                            </Select.Item>
                          ))}
                        </Select.Content>
                      </Select.Positioner>
                    </Select.Root>
                  </Field>
                </VStack>
              </Box>

              {/* ── Custom CSS OBS ── */}
              <Box
                p={5}
                bg="white"
                _dark={{ bg: "gray.800" }}
                borderRadius="xl"
                shadow="sm"
              >
                <Heading size="sm" mb={3}>
                  💻 Code CSS OBS
                </Heading>
                <Text fontSize="sm" color="gray.500" mb={4}>
                  Copiez ce code et collez-le dans le champ "CSS personnalisé"
                  de votre source navigateur YouTube Chat sur OBS.
                </Text>

                <Box position="relative">
                  <Box
                    as="pre"
                    p={4}
                    bg="gray.900"
                    color="green.400"
                    borderRadius="md"
                    fontSize="xs"
                    overflowX="auto"
                    maxH="200px"
                    overflowY="auto"
                    fontFamily="mono"
                  >
                    {generateYoutubeCSS(config)}
                  </Box>
                  <Button
                    position="absolute"
                    top={2}
                    right={2}
                    size="sm"
                    colorPalette="gray"
                    variant="surface"
                    onClick={() => {
                      navigator.clipboard.writeText(generateYoutubeCSS(config));
                      toaster.create({
                        title: t('common.copied'),
                        description:
                          "Le CSS a été copié dans le presse-papier.",
                        type: "success",
                      });
                    }}
                  >
                    <FiCopy /> Copier
                  </Button>
                </Box>
              </Box>
            </VStack>
          </GridItem>
        </Grid>
      </Container>
    </Box>
  );
}
